### ISSUE TITLE
Bug in FPR function

### ISSUE THREAD

**Issue by matthaeusheer** [StefanDenn3r/Unsupervised_Anomaly_Detection_Brain_MRI#3]
Hey guys

I found a bug in the false positive rate function at
https://github.com/StefanDenn3r/Unsupervised_Anomaly_Detection_Brain_MRI/blob/40085a830ee6aae9a3cacc8145f15e62dfa83bc7/trainers/Metrics.py#L89

The FPR = fp / (fp + tn), not fp / (fp + tp), which is actually precision.

Not sure if you care but I thought I give notice nonetheless!

Cheers

**Comment by StefanDenn3r** [comment]
Hi @matthaeusheer, 
thank you very much for pointing this out! 
I just fixed it with commit https://github.com/StefanDenn3r/Unsupervised_Anomaly_Detection_Brain_MRI/commit/dab03d71c164e8c7dbcb44e2d79a5a8a2fd0f5db.

Cheers!
