### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by mighty-phoenix** [StefanDenn3r/Unsupervised_Anomaly_Detection_Brain_MRI#6]
Hey @StefanDenn3r !
Can you please add the test results of your model to the readme file?
That'll be very helpful.
Thanks!

**Comment by StefanDenn3r** [comment]
Hi @mighty-phoenix, 
thanks for your comment. 
Test results can be taken from our [paper](https://arxiv.org/pdf/2004.03271.pdf).

Cheers!

**Comment by mighty-phoenix** [comment]
Oh, thanks!
I just went through the paper.
Thanks again!
@StefanDenn3r
