### ISSUE TITLE
Is normalization used in the results in the paper?

### ISSUE THREAD

**Issue by sten2lu** [StefanDenn3r/Unsupervised_Anomaly_Detection_Brain_MRI#7]
Unsupervised_Anomaly_Detection_Brain_MRI/models/customlayers.py 
-->  `build_unified_encoder` & `build_unified_decoder` 
both have the default value: `use_batchnorm=True`

I am a bit confused since as far as I see this value is not overridden for VAE and Autoencoder.
But in the visulalisation in your [paper](http://arxiv.org/abs/2004.03271) and also in general I could not find any mention of it

**Comment by StefanDenn3r** [comment]
Hi @sten2lu, 
sorry for the late response and thank you for your question. 
We tried out using batch normalization but the performance didn't change significantly. 
All results in the paper are **without** using batch normalization. 

Cheers,
Stefan
